language: node_js
node_js:
  - "10"
deploy:
  provider: npm
  email: cardinalby@gmail.com
  skip_cleanup: true
  api_key:
    secure: WY5MbdADYVwaSd+C4v2Gy3E9odFmyMTFLAftXe5v6IqkqYXogVlhF2SZ5Mwn2FCDLnLbcD8W+ovhpU7HIG4rl07clg713uxLPcOQqRAthbMKAHzD9rv1uNq44EQFThp1dbi4Z8q33rrBfXra9bNtyqamVGUXFpVddot/x2YSbhGr5MPza5MllcivxllIHzvZUE7rfRs6kZ2mBUtXSHFauaR9rtVs0S7BY5UCnhEW93EXF/b9JKMKhDulUxH4Y1UV0CESTsTudIIWZoMov7ZwZ2phGtOX7exncxKXkyDhDEfGuW5c2ZSiVqJ4aI7eQCrVyWEIDFXOJcKehyEEkhxAaCFUVae7prjbYuNwOe3/Zdu8Q73TZO0eiBC3jmsU+BvSTENc0yI0Vw3QjxiylJlsWGeKA9wTEUadeftb9u379ABr+RISWh8G3bxU2yz65qwW/jXYksRSBmxR52v3xTe5VGnr2MX3RKXUPFq+5+6UKpg31UAJC9+i8drCjJjNRC0rJdrOcxtS2jmx/M2dnZTr80OppVmcfClok1hW9VUQPTYnJ/Fi/S6IyUclWuBFViKt9A9uc+nZ+I/AIT6jTwh6OZKWula5D1cjvP0qgLocNbFLV3zC1E3Ixney33TUWjwf33y9LAEytXORcTBGdtpj38gYhWelH/MCWVb1DFElWaM=
  on:
    tags: true
    repo: cardinalby/ts-raii-scope